# Generated by Django 4.2.5 on 2023-10-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Dairy', 'Dairy')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('TRACKPANT', 'TRACKPANT'), ('PALAZZO', 'PALAZZO'), ('LJEANS', 'LEDIES JEANS'), ('GJEANS', 'GENTS JEANS'), ('SHIRT', 'SHIRT'), ('PANT', 'PANT'), ('SHORTS', 'SHORTS'), ('SKIRT', 'SKIRT'), ('INNER', 'INNER'), ('SAREE', 'SAREE'), ('JACKET', 'JACKET'), ('LEGGING', 'LEGGING'), ('CURD', 'CURD'), ('MILK', 'MILK'), ('LASSI', 'LASSI'), ('MILKSHAKE', 'MILKSHAKE'), ('GHEE', 'GHEE'), ('PANEER', 'PANEER'), ('CHEESE', 'CHEESE'), ('ICE', 'ICE-CREAME')], max_length=100)),
                ('product_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=100)),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('main_catetory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
